### ISSUE TITLE
the rotation and translation matrix in calibration file 

### ISSUE THREAD

**Issue by AOOOOOA** [mmmmaomao/DataGenerator#3]
Thanks for your work! It is useful and helps a lot. 

But I have a few questions about the R and T matrix in calib files. Since I found out that the P0, P1..., R0_rect, Tr_velo_to_cam, and Tr_imu_to_velo in all calib files are the same. Are they the real value in Carla world or just some pre-defined value?

**Comment by mmmmaomao** [comment]
It's just a pre-defined value since I didn't use it.









王杰

北京邮电大学/研究生/计算机学院（国家示范性软件学院）



北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, May 16, 2022 00:30 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[mmmmaomao/DataGenerator] the rotation and translation matrix in calibration file  (Issue #3)

&nbsp;



 
Thanks for your work! It is useful and helps a lot.
 
But I have a few questions about the R and T matrix in calib files. Since I found out that the P0, P1..., R0_rect, Tr_velo_to_cam, and Tr_imu_to_velo in all calib files are the same. Are they the real value in Carla world or just some pre-defined value?

**Comment by AOOOOOA** [comment]
Thanks, I have already solved it.
